- docs/source/getting_started.rst
- docs/source/install.rst
- docs/source/prereqs.rst
Translation of Chapter 2 (Getting Started, Prerequisites and Install), please review and merge, thanks.
> 1.2.0 zh cn

- docs/source/blockchain.rst
- docs/source/fabric_model.rst
- docs/source/functionalities.rst
- docs/source/key_concepts.rst
This is translation of Key Concept - Functionalities, please review and merge. Thanks a lot.
> 1.2.0 zh cn: Translation of Key Concept - Functionalities

- docs/source/glossary.rst
I have translated Glossary according to the Fabric 1.1 version cn.
Translation can refer to this later, so please review carefully and check if it is appropriate before merge it. Thanks a lot.
> 1.2.0 zh cn: Translation of Glossary.

- docs/source/network/network.md
Translation of network, please review and merge, thanks.
> 1.2.0 zh cn: Translation of Key Concept - Network

- docs/source/index.rst
Adapt the translation to the new index.rst in this repo. 
Refer to the original commits in the old repo:
https://github.com/HyperledgerCN/fabric-docs-i18n/pull/6
> update translation for index.rst

- docs/source/commands/configtxlator.md
Signed-off-by: 立冬 郭 <guolidong@chainnova.com>
> Translate configtxlator command document

- docs/README.md
- docs/source/private-data/private-data.md
Signed-off-by: 立冬 郭 <guolidong@chainnova.com>
> Translate Key Concept of Private Data

- docs/source/understand_fabcar_network.rst
Signed-off-by: 立冬 郭 <guolidong@chainnova.com>
> Translate fabcar

- README.md
- docs/source/ledger.rst
- docs/source/ledger/ledger.md
- docs/source/usecases.rst
Translation for Hyperledger Fabric:
Key Concepts - Ledger
Key Concepts - Use Cases
> 1.3.0 zh cn

- docs/source/users-guide.rst
> translate a part of users-guide.rst

- docs/source/users-guide.rst
> translate a part of users-guide.rst : Rearrange the list

- docs/source/users-guide.rst
> translate a part of users-guide.rst : Rearrange 'Getting Idemix CRI'

- docs/source/users-guide.rst
> translate a part of users-guide.rst : complete content

- docs/source/users-guide.rst
- swagger/swagger-fabric-ca.json
> translate a part of users-guide.rst : table content & overview

- docs/source/private-data-arch.rst
> Translate Architecture Reference - Private Data

- docs/source/users-guide.rst
> translate a part of users-guide.rst : Prerequisites

- docs/source/blockchain.rst
- docs/source/key_concepts.rst
- docs/source/membership/membership.md
> Minor changes to remove some typos

- docs/source/peers/peers.md
> Translate Key Concept - Peers

- docs/source/glossary.rst
> Translate some new items on glossary

- docs/source/network/network.md
> Translate key concept Blockchain network

- docs/source/membership/membership.md
> Translate key concept Membership

- docs/source/developapps/developing_applications.rst
Close #133 Translate Developing Applications: Developing Applications, the translation is done.
> close #133

- docs/.gitignore
- docs/source/whatis.md
>  close issue Translate Update V1.4: Introduction:Introduction #122

- docs/source/whatis.md
close issue Translate Update V1.4: Introduction:Modularity #124
> close issue Translate Update V1.4: Introduction:Modularity #124

- docs/source/developapps/scenario.md
Translate is done. Please check.
> Closes #135,#136 Translate Developing Applications: The scenario

- docs/source/whatis.md
close issue Translate Update V1.4: Introduction:Permissioned vs Permissionless Blockchains #125
> close issue Translate Update V1.4: Introduction:Permissioned vs Permissionless Blockchains #125

- docs/source/developapps/analysis.md
> Translate Developing Applications: Analysis is done

- docs/source/whatis.md
close issue #126
close issue #127 
> close issue 

- docs/source/developapps/architecture.md
Signed-off-by: shniu <xiaoniu198903@126.com>
> close #145

- docs/source/whatis.md
>  close issue #128

- docs/source/whatis.md
close issue #130
close issue #131
close issue #132
> translate done three sections in whatis.md

- docs/source/developapps/architecture.md
- docs/source/developapps/transactionhandler.md
Signed-off-by: shniu <xiaoniu198903@126.com>
> close #164

- docs/source/Fabric-FAQ.rst
- docs/source/blockchain.rst
- docs/source/capability_requirements.rst
- docs/source/discovery-overview.rst
- docs/source/fabric_model.rst
- docs/source/functionalities.rst
- docs/source/glossary.rst
- docs/source/identity/identity.md
- docs/source/index.rst
- docs/source/key_concepts.rst
- docs/source/ledger/ledger.md
- docs/source/membership/membership.md
- docs/source/network/network.md
- docs/source/peers/peers.md
- docs/source/private-data-arch.rst
- docs/source/private-data/private-data.md
- docs/source/usecases.rst
> Translate FAQ for V1.4

- docs/source/whatsnew.rst
close issue #183
close issue #184
> close issue

- docs/source/tutorial/commercial_paper.md
Signed-off-by: shniu <xiaoniu198903@126.com>
> Part of the issue #151, Working as MagnetoCorp

- docs/source/tutorial/commercial_paper.md
Signed-off-by: shniu <xiaoniu198903@126.com>
> Part of the issue #151, Smart contract

- docs/source/install.rst
- docs/source/prereqs.rst
> close issue #215

- README.md
- docs/source/CONTRIBUTING.rst
Signed-off-by: TopJohn <xzj19922010@gmail.com>
> translate the contribution doc

- docs/source/write_first_app.rst
finish translate #236 #237 #238 #239
> finish translate Translation-Docs » Tutorials » Writing Your First Application

- docs/source/index.rst
- docs/source/users-guide.rst
Signed-off-by: 郭 立冬 <guolidong@chainnova.com>
> translate some sections of users-guide

- docs/source/users-guide.rst
Signed-off-by: 郭 立冬 <guolidong@chainnova.com>
> translate configure LDAP sections

- docs/source/dev-setup/devenv.rst
- docs/source/developapps/analysis.md
- docs/source/developapps/application.md
- docs/source/developapps/architecture.md
Signed-off-by: 郭 立冬 <guolidong@chainnova.com>
> add left 2.0.0 alpha content

- docs/source/kafka.rst
>  Finished issue #317 #318 #319

- docs/source/chaincode4ade.rst
- docs/source/chaincode4noah.rst
- docs/source/systemchaincode.rst
> finished #333 #334 #335

- docs/source/arch-deep-dive.rst
- docs/source/architecture.rst
- docs/source/network/network.md
- docs/source/private_data_tutorial.rst
fix some errors in 1.4.0_zh-CN
> fix some errors in 1.4.0_zh-CN

- docs/source/commands/configtxgen.md
- docs/source/commands/cryptogen.md
Signed-off-by: pszzz <mayilong1989@hotmail.com>
> translate cryptogen.md configtxgen.md

- docs/source/commands/configtxgen.md
- docs/source/commands/cryptogen.md
Reverts hyperledger-labs/fabric-docs-cn#371
> Revert "translate cryptogen.md configtxgen.md"

- docs/source/raft_configuration.md
Signed-off-by: Pluton Ji <plutonji@163.com>
#366
> Translate raft_configuration

- docs/source/developapps/connectionoptions.md
docs/source/developapps/connectionoptions.md was translated  by ZHAOBIAO（sa515092@mail.ustc.edu.cn）
> 1.4.2 zh_cn translation

- docs/source/commands/peerchannel.md
Signed-off-by: Shitaibin <hz_stb@163.com>
> Translate peer channel command

- docs/source/msp.rst
Signed-off-by: pszzz <mayilong1989@hotmail.com>
> translate msp.rst

- docs/source/config_update.md
Signed-off-by: tomxucnxa <170015@qq.com>
> Translate config_update.md

- docs/source/developapps/chaincodenamespace.md
- docs/source/kafka_raft_migration.md
Signed-off-by: Fengcheng960512 <chengfeng960512@hotmail.com>
> chaincodenamespace

- docs/source/build_network.rst
Reverts hyperledger-labs/fabric-docs-cn#442
> Revert "merge"

- docs/source/blockchain.rst
- docs/source/fabric_model.rst
- docs/source/functionalities.rst
- docs/source/identity/identity.md
- docs/source/membership/membership.md
- docs/source/network/network.md
- docs/source/orderer/ordering_service.md
- docs/source/peers/peers.md
- docs/source/private-data/private-data.md
- docs/source/smartcontract/smartcontract.md
Translate for:
- release-2.0: Key Concepts » Introduction
- release-2.0: Key Concepts » Hyperledger Fabric Functionalities
- release-2.0: Key Concepts » Hyperledger Fabric Model
- release-2.0: Key Concepts » Blockchain network
- release-2.0: Key Concepts » Identity
- release-2.0: Key Concepts » Membership
- release-2.0: Key Concepts » Peers
- release-2.0: Key Concepts » Smart Contracts and Chaincode
- release-2.0: Key Concepts » The Ordering Service
- release-2.0: Key Concepts » Private data
> Release 2.0 - Key Concepts

- docs/source/usecases.rst
Signed-off-by: wtb <tianbowu@gmail.com>
> translation of use cases.

- docs/source/usecases.rst
review translation. #574 release-2.0: Key Concepts » Use Cases
> Release 2.0

- docs/source/whatsnew.rst
Signed-off-by: bessieIsBinBIn <hubinmei666666@gmail.com>
> translation of what's new in Hyperledfer Fabric v2.0

- docs/source/developapps/analysis.md
- docs/source/developapps/application.md
- docs/source/developapps/architecture.md
- docs/source/developapps/designelements.rst
- docs/source/developapps/developing_applications.rst
- docs/source/developapps/scenario.md
- docs/source/getting_started.rst
- docs/source/install.rst
- docs/source/prereqs.rst
- docs/source/write_first_app.rst
Translate release-2.0: Getting Started
Translate release-2.0: Getting Started » Prerequisites
Translate release-2.0: Getting Started » Install Samples, Binaries
> Release 2.0 - Getting Start

- docs/source/capability_requirements.rst
- docs/source/channels.rst
Signed-off-by: tywang <125801169@qq.com>
> capability_requirements is translated

- docs/source/discovery-overview.rst
Signed-off-by: tywang <125801169@qq.com>
> discovery-overview is translated

- docs/source/enable_cc_lifecycle.md
Signed-off-by: SusieZY <susie_zhng@163.com>
> Translation of "release 2.0 enable_cc_lifecycle.md" #509

- .readthedocs.yml
Signed-off-by: Yang Cheng <chengyang418@163.com>
> add .readthedocs.yml for not building pdf

- docs/source/commands/peerlifecycle.md
anyone can help to review my PR for the issue #506?
> Release-2.0: Commands Reference » peer lifecycle chaincode #506

- .github/settings.yml
Don't merge until content is migrated
Signed-off-by: Ry Jones <ry@linux.com>
> Archive repo
